### PR TITLE
Add server response log when status code error

### PR DESCRIPTION
**Pull request by WarleyGabriel**
This pull request solve this issue: https://github.com/visionmedia/supertest/issues/631

### CODE REVIEW

**Comment by niftylettuce** [comment]
I think this would be a pretty big breaking change, hmm

**Comment by danilofuchs** [comment]
Why would this be a breaking change? It makes the assertions more useful for debugging, but does not affect the assertion itself. A test that does not pass will continue not passing, but now with more info

**Comment by niftylettuce** [comment]
I think this is a breaking change because one would normally expect the error messages to be much shorter.

I also think that stringifying the body in the message is probably bad practice, as the body could be a huge response payload (e.g. HTML by accident instead of JSON).  I think perhaps declaring the error, e.g. `const err = new Error(...)` and then making a private property on it, such as `err._res = res` would be more useful.

**Comment by WarleyGabriel** [comment]
Since this is not gonna be merged, closing it.

**Pull request closed without merging**
